### ISSUE TITLE
[Bug]:合并表头后边框显示不全

### ISSUE THREAD

**Issue by SLiGe** [CcSimple/vue-plugin-hiprint#137]
### 使用的版本

latest

### 版本号

0.0.56

### 你的安装方式

NPM 依赖

### 你的操作系统

Windows

### 你的浏览器

Chrome

### 你的项目编程语言

Vue 3

### 问题描述

设计页面是直接从npm_demo_v3复制来的，当合并的表头列过多时边框就显示异常了，如下图：
![image](https://github.com/user-attachments/assets/c374db84-6740-44d0-85b4-72376b1f791a)
![image](https://github.com/user-attachments/assets/67f74c40-2738-4562-8e6f-ef5ba9e9d13e)
左侧边框丢失。

### 如何复现

1. 创建一个空表格
2. 添加16个列，2行表头
3. 合并表头

### 预期结果

表头列边框显示正常

### 实际结果

某个表头列边框丢失

### 截图或视频

[在这里上传图片]

### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://github.com/CcSimple/vue-plugin-hiprint/issues)

**Comment by SLiGe** [comment]
不知道什么原因引入``print-lock.css``没有生效，加上以下css就正常了
```css
<style lang="less" scoped>
  /deep/ .hiprint-printElement-tableTarget-border-td-all td:not(last-child) {
    border-right: 1px solid;
  }
</style>
```
