### ISSUE TITLE
表格合并列后无法自动撑满整个容器

### ISSUE THREAD

**Issue by Xavier9896** [CcSimple/vue-plugin-hiprint#69]
![image](https://github.com/CcSimple/vue-plugin-hiprint/assets/34981520/d05cfd04-bf5d-4653-a6a9-2aa53bc80b52)
添加如下css即可解决
```css
table.hiprint-printElement-tableTarget.hitable {
  width: 100%;
}
```
